### ISSUE TITLE
Criar tela de cadastro

### ISSUE THREAD

**Issue by Pedrok99** [fga-eps-mds/2022-1-schedula-front#2]
- [x] Criar tela de cadastro de acordo  com o [figma](https://www.figma.com/file/Z1nuHq7xWWKRlntLN07fvQ/Prototipo-de-alta-fidelidade-(Copy)?node-id=39%3A24)
- [ ] Implementar lógica para realização de requisições de criação de usuário.
- [x] Adicionar validações básicas no formulário (Ex: Número no nome, etc...)
- [ ] Criar testes unitarios com react-testing-library

**Comment by EduardoPicolo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-front/2?planning-poker) with ZenHub @Pedrok99
