### ISSUE TITLE
Criar e editar cidades

### ISSUE THREAD

**Issue by Pedrok99** [fga-eps-mds/2022-1-schedula-front#26]
Pré-requisitos: Issue #25 completa

- [x] Criar modal para criação de cidades ( baseados no protótipo de alta fidelidade )
  - [x]  Implementar lógica de requisição de criação para o micro-serviço responsável
  - [x]  Atualizar visualmente a página
- [x] Criar modal para edição de cidades ( baseados no protótipo de alta fidelidade )
  - [x]  Implementar lógica de requisição para o micro-serviço responsável
  - [x]  Atualizar visualmente a página

**Comment by RodrigoWright** [comment]
cadastro: https://www.figma.com/file/Z1nuHq7xWWKRlntLN07fvQ/Prototipo-de-alta-fidelidade-(Copy)?node-id=415%3A650 
editar: https://www.figma.com/file/Z1nuHq7xWWKRlntLN07fvQ/Prototipo-de-alta-fidelidade-(Copy)?node-id=415%3A1360
