### ISSUE TITLE
Excluir cidades

### ISSUE THREAD

**Issue by Pedrok99** [fga-eps-mds/2022-1-schedula-front#27]
Pré-requisitos: Issue #25  completa

- [x] Criar modal de confirmação de exclusão de cidade
- [x] Implementar requisição de exclusão para o micro-serviço responsável
- [x] Atualizar visualmente ao remover uma cidade

**Comment by RodrigoWright** [comment]
Deletar: https://www.figma.com/file/Z1nuHq7xWWKRlntLN07fvQ/Prototipo-de-alta-fidelidade-(Copy)?node-id=415%3A1503
